// var Peo = require('peo')
var Peo = require('../src/Peo')

console.log(``)
var peo = new Peo(360, 77)
console.log(`var peo = new Peo(360, 77) - a normal sized fraction`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}  (string)`)
console.log(`peo.getNum() returns ${peo.getNum()}  (integer)`)
console.log(`peo.getDenom() returns ${peo.getDenom()}  (integer)`)
console.log(`peo.getVal() returns ${peo.getVal()}  (decimal)`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)

console.log(``)
var peo = new Peo({2:123456789, 3:-654321})
console.log(`var peo = new Peo({2:123456789, 3:-654321}) - a large number, requires exponent representation`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)


console.log(``)
var peo = Peo.fact(50)
console.log(`var peo = Peo.fact(50) - a factorial beyond integer representation`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)

console.log(``)
var peo = Peo.prim(50)
console.log(`var peo = Peo.prim(50) - a primorial also beyond integer representation`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)

console.log(``)
var peo = Peo.binom(100, 35)
console.log(`var peo = Peo.binom(100, 35) - a factorial beyond integer representation`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)

console.log(``)
var peo = Peo.binom(284, 28)
console.log(`var peo = Peo.binom(284, 28) - a factorial beyond integer representation`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)

console.log(``)
var peo = Peo.fact(109, 9)
console.log(`var peo = Peo.fact(109, 9) - equivalent to 109*108*107*106*105*104*103*102*101`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)

console.log(``)
var peo = Peo.fact(101, 5, 2)
console.log(`var peo = Peo.fact(101, 5, 2) - equivalent to 101*103*105*107*109`)
console.log(``)
console.log(`peo.getText() returns ${peo.getText()}`)
console.log(`peo.getNum() returns ${peo.getNum()}`)
console.log(`peo.getDenom() returns ${peo.getDenom()}`)
console.log(`peo.getVal() returns ${peo.getVal()}`)
console.log(`peo.getPrimeExps() returns ${JSON.stringify(peo.getPrimeExps())}`)
console.log(``)
console.log(peo)
console.log(``)
